package pojo;
// Generated Oct 11, 2023 5:22:53 PM by Hibernate Tools 4.3.1

import DAO.DAOAdmin;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;




/**
 * Admin generated by hbm2java
 */

@ManagedBean
public class Admin  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String password;

    public Admin() {
    }

    public Admin(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String validatelogin()
    { 
        try {
            DAOAdmin pdao=new DAOAdmin();
            List<Admin> prod=pdao.validateLogin(username, password);
            username=prod.get(0).username;
            password=prod.get(0).password;
            
            FacesContext context = FacesContext.getCurrentInstance();
            if(username != null) {
                context.getExternalContext().getSessionMap().put("username", username);
                return "success";
            }
            else {
                return "error";
            }
        }
        catch(Exception ex) {
            return "error";
        }
        //return prod;
    }
    


}