package pojo;
// Generated Oct 11, 2023 5:22:53 PM by Hibernate Tools 4.3.1
import DAO.DAOPendaftaran;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.faces.bean.ManagedBean;



/**
 * Pendaftaran generated by hbm2java
 */

@ManagedBean
public class Pendaftaran  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String tempatlahir;
     private String tgllahir;
     private String alamat;
     private String email;
     private String nohp;
     private String asalsekolah;

    public Pendaftaran() {
    }

    public Pendaftaran(String nama, String tempatlahir, String tgllahir, String alamat, String email, String nohp, String asalsekolah) {
       this.nama = nama;
       this.tempatlahir = tempatlahir;
       this.tgllahir = tgllahir;
       this.alamat = alamat;
       this.email = email;
       this.nohp = nohp;
       this.asalsekolah = asalsekolah;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getTempatlahir() {
        return this.tempatlahir;
    }
    
    public void setTempatlahir(String tempatlahir) {
        this.tempatlahir = tempatlahir;
    }
    public String getTgllahir() {
        return this.tgllahir;
    }
    
    public void setTgllahir(String tgllahir) {
        this.tgllahir = tgllahir;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNohp() {
        return this.nohp;
    }
    
    public void setNohp(String nohp) {
        this.nohp = nohp;
    }
    public String getAsalsekolah() {
        return this.asalsekolah;
    }
    
    public void setAsalsekolah(String asalsekolah) {
        this.asalsekolah = asalsekolah;
    }

public String save()
    {
        DAOPendaftaran pdao=new DAOPendaftaran();
        pdao.addPendaftaran(this);
        return "show.xhtml";
    }

    public String delete()
    {    
        DAOPendaftaran pdao=new DAOPendaftaran();
        pdao.deletePendaftaran(id);
        return "show.xhtml";
    } 
    public List<Pendaftaran> getbyid()
    { 
        DAOPendaftaran pdao=new DAOPendaftaran();
        List<Pendaftaran> prod=pdao.getbyID(id);
        nama=prod.get(0).nama;
        tempatlahir=prod.get(0).tempatlahir;
        tgllahir=prod.get(0).tgllahir;
        alamat=prod.get(0).alamat;
        email=prod.get(0).email;
        nohp=prod.get(0).nohp;
        asalsekolah=prod.get(0).asalsekolah;
        return prod;
    }


    public List<Pendaftaran> getallrecords()
    {
        DAOPendaftaran pdao=new DAOPendaftaran();
        List<Pendaftaran> prod=pdao.retrievePendaftaran();
        return prod;
    }

    public String update()
    {
        DAOPendaftaran pdao=new DAOPendaftaran();
        pdao.updatePendaftaran(this);
        return "show.xhtml";
    }



}